config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :donuts, only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:new, :create, :new, :update]
    resources :reviews, only: [:new, :create]
    resources :donut_tags, only: [:new, :create]
  end

  resources :donut_tags, only: [:destroy]

  resources :orders, only: [:index, :show]

  get :account, to: "pages#account"
  get :bakery, to: "pages#bakery"
  get :archived, to: "pages#archived"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky d-block" >
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <p>D<%= image_tag "pink_logo_donut.jpg" %>NUT DASH</p>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "All Donuts", donuts_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Your Purchases", account_path, class: "dropdown-item" %>
              <% if current_user.baker %>
                <%= link_to "Your Bakery", bakery_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>