config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :donuts, only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:new, :create, :new, :update]
    resources :reviews, only: [:new, :create]
    resources :donut_tags, only: [:new, :create]
  end

  resources :donut_tags, only: [:destroy]

  resources :orders, only: [:index, :show]

  get :account, to: "pages#account"
  get :bakery, to: "pages#bakery"
  get :archived, to: "pages#archived"
end

app/views/pages/account.html.erb
<h2 id="your-page-title"><%= current_user.first_name %>'s Active Orders</h3>
<div class='container'>
  <div class="d-flex justify-content-around p-3">

    <div style="min-width: 430px;">
      <h3 class="d-flex justify-content-around p-3">Pending Orders</h3>
      <% @pending_orders.each do |order| %>
        <div class='card big-white-container user-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>
            <p>Status: <%= order.complete ? "complete" : order.status %></p>
          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 150, height: 150, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h3 class="d-flex justify-content-around p-3">Accepted Orders</h3>
      <% @accepted_orders.each do |order| %>
        <div class='card big-white-container user-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>
            <p>Status: <%= order.complete ? "complete" : order.status %></p>
          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 150, height: 150, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h3 class="d-flex justify-content-around p-3">Out For Delivery</h3>
      <% @delivery_orders.each do |order| %>
        <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>
            <p>Status: <%= order.complete ? "complete" : order.status %></p>
          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 150, height: 150, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h3 class="d-flex justify-content-around p-3">Delivered</h3>
      <% @complete_orders.each do |order| %>
        <div class='card big-white-container user-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>
            <p>Status: <%= order.complete ? "complete" : order.status %></p>
            <%= link_to "Leave Review", new_donut_review_path(order.donut_id)  %>
          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 150, height: 150, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/archived.html.erb
<div style="min-width: 430px;">
  <h2>Archived Orders</h2>
  <% @archived_orders.each do |order| %>
    <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
      <div>
        <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
        <% total = order.total_cost.round(2).to_s.split(".") %>
        <% if total[1].length == 1 %>
          <% total[1] = total[1] + "0" %>
        <%end%>
        <% total = total.join(".") %>
        <p>Total: £<%= total %></p>
        <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>


        <div class="nav-link dropdown">
          <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Customer Info
          </span>
          <div class="dropdown-menu dropdown-menu-begin" aria-labelledby="navbarDropdown">
            <div class="container" style="width: 200px;">
              <p><%= order.user.first_name %> <%= order.user.last_name %></p>
              <p><%= order.user.address %></p>
              <p><%= order.user.phone_number %></p>
            </div>
          </div>
        </div>


      </div>
      <div>
        <%= cl_image_tag(order.donut.photo.key, width: 100, height: 100, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
      </div>
      <div class="nav-link dropdown">
        <p>Status:</p>
        <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Complete
        </span>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <div class="container" style="width: 180px;">
            <%= render "orders/baker_edit_form", donut: order.donut, order: order %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/bakery.html.erb
<h2 id="your-page-title"><%= current_user.first_name %>'s Orders</h2>
<h4 id="your-page-title"><%= link_to "Go to Archive", archived_path, class:"button-in-title" %></h4>
<div class="container d-flex justify-content-center flex-column top-spacing-small">
  <div class="d-flex justify-content-center">

    <div style="min-width: 430px;">
      <h2 style="text-align: center;">Incoming Orders</h2>
      <% @pending_orders.each do |order| %>
        <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>

            <div class="nav-link dropdown">
              <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Customer Info
              </span>
              <div class="dropdown-menu dropdown-menu-begin" aria-labelledby="navbarDropdown">
                <div class="container" style="width: 200px;">
                  <p><%= order.user.first_name %> <%= order.user.last_name %></p>
                  <p><%= order.user.address %></p>
                  <p><%= order.user.phone_number %></p>
                </div>
              </div>
            </div>

          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 100, height: 100, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
          <div class="nav-link dropdown">
            <p>Status:</p>
            <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= order.status %>
            </span>
            <div class="dropdown-menu dropdown-menu-start" aria-labelledby="navbarDropdown">
              <div class="container" style="width: 180px;">
                <%= render "orders/baker_edit_form", donut: order.donut, order: order %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h2 style="text-align: center;">Accepted Orders</h2>
      <% @accepted_orders.each do |order| %>
        <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>

            <div class="nav-link dropdown">
              <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Customer Info
              </span>
              <div class="dropdown-menu dropdown-menu-begin" aria-labelledby="navbarDropdown">
                <div class="container" style="width: 200px;">
                  <p><%= order.user.first_name %> <%= order.user.last_name %></p>
                  <p><%= order.user.address %></p>
                  <p><%= order.user.phone_number %></p>
                </div>
              </div>
            </div>

          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 100, height: 100, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
          <div class="nav-link dropdown">
            <p>Status:</p>
            <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= order.status %>
            </span>
            <div class="dropdown-menu dropdown-menu-start" aria-labelledby="navbarDropdown">
              <div class="container" style="width: 180px;">
                <%= render "orders/baker_edit_form", donut: order.donut, order: order %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h2 style="text-align: center;">Out for delivery</h2>
      <% @delivery_orders.each do |order| %>
        <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>

            <div class="nav-link dropdown">
              <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Customer Info
              </span>
              <div class="dropdown-menu dropdown-menu-begin" aria-labelledby="navbarDropdown">
                <div class="container" style="width: 200px;">
                  <p><%= order.user.first_name %> <%= order.user.last_name %></p>
                  <p><%= order.user.address %></p>
                  <p><%= order.user.phone_number %></p>
                </div>
              </div>
            </div>


          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 100, height: 100, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
          <div class="nav-link dropdown">
            <p>Status:</p>
            <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= order.status %>
            </span>
            <div class="dropdown-menu dropdown-menu-start" aria-labelledby="navbarDropdown">
              <div class="container" style="width: 180px;">
                <%= render "orders/baker_edit_form", donut: order.donut, order: order %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div style="min-width: 430px;">
      <h2 style="text-align: center;">Fulfilled Orders</h2>
      <% @complete_orders.each do |order| %>
        <div class='card big-white-container baker-order-card d-flex flex-row justify-content-around align-items-center'>
          <div>
            <p><b><%= order.donut.name %></b> x <%= order.quantity %></p>
            <% total = order.total_cost.round(2).to_s.split(".") %>
            <% if total[1].length == 1 %>
              <% total[1] = total[1] + "0" %>
            <%end%>
            <% total = total.join(".") %>
            <p>Total: £<%= total %></p>
            <p>Order date: <br> <%= order.created_at.strftime('%d-%m-%Y %H:%M') %></p>

            <div class="nav-link dropdown">
              <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Customer Info
              </span>
              <div class="dropdown-menu dropdown-menu-begin" aria-labelledby="navbarDropdown">
                <div class="container" style="width: 200px;">
                  <p><%= order.user.first_name %> <%= order.user.last_name %></p>
                  <p><%= order.user.address %></p>
                  <p><%= order.user.phone_number %></p>
                </div>
              </div>
            </div>


          </div>
          <div>
            <%= cl_image_tag(order.donut.photo.key, width: 100, height: 100, crop: :fill , alt: order.donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          </div>
          <div class="nav-link dropdown">
            <p>Status:</p>
            <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Complete
            </span>
            <div class="dropdown-menu dropdown-menu-start" aria-labelledby="navbarDropdown">
              <div class="container" style="width: 180px;">
                <%= render "orders/baker_edit_form", donut: order.donut, order: order %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h2 id="your-page-title" class="top-spacing"><%= current_user.first_name %>'s Donuts</h3>
<h4 id="your-page-title"><%= link_to "Add Donut", new_donut_path, class:"button-in-title" %></h4>
<div class="container d-flex justify-content-between flex-column top-spacing-small">
  <div class="d-flex justify-content-around">
      <% current_user.donuts.each do |donut| %>
        <div class="card big-white-container m-1" style="width: 18rem;">

          <div class="card-body">
            <h5><strong><%= donut.name%></strong></h5>
          </div>

          <%= link_to donut_path(donut) do %>
            <%= cl_image_tag(donut.photo.key, width: 600, height: 600, crop: :fill , alt: donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
          <% end %>

          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"> <%= image_tag "donut-c.png", width: 20, height: 20 %> <%= donut.rating>0 ? "#{donut.rating} (#{donut.number_ratings})" : "N/A" %></li>
              <li class="list-group-item">£ <%= donut.price%></li>

              <li class="list-group-item">
                <div class="nav-link dropdown">
                  <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= donut.available? ? "Available" : "Not available" %>
                  </span>
                  <div class="dropdown-menu dropdown-menu-" aria-labelledby="navbarDropdown">
                    <div class="container" style="width: 180px;">
                      <%= render "donuts/donut_availability_edit_form", donut: donut %>
                    </div>
                  </div>
                </div>
              </li>

              <li class="list-group-item">
                <div class="nav-link dropdown">
                  <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Tags
                  </span>
                  <div class="dropdown-menu dropdown-menu-start" aria-labelledby="navbarDropdown">
                    <div class="container" style="width: 250px;">
                      <%= render "donut_tags/form", donut: donut, donut_tag: DonutTag.new %>
                    </div>
                  </div>
                </div>

                <% donut.donut_tags.each do |donut_tag| %>
                  <%= donut_tag.tag.name %> <%= link_to "X", donut_tag_path(donut_tag), data: {
                                              turbo_method: :delete,
                                              turbo_confirm: "Are you sure you want to remove your #{donut_tag.tag.name} tag?"
                                              }
                                            %><br>
                <% end %>
              </li>

              <li class="list-group-item"><%= link_to "Edit Details", edit_donut_path(donut) %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1 id="home-page-title">We are home to the most delicious donuts you've ever tasted</h1>
<div class="container mt-3 mb-3 big-white-container">
    <div class="d-flex flex-row">
      <div class="col-8 p-3 justify-content-center">
        <h3 style="float: right; margin-left: 20px;" class="title-search-bar m-2">Mmm...Donuts!</h3>
          <%= form_with url: donuts_path, method: :get, class: "d-flex m-2" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "search-form form-control p-2 shadow",
              placeholder: "Find your donut"
            %>
            <%= submit_tag "Search", class: "btn searchbar-button p-1 shadow" %>
          <% end %>
      </div>
      <div class="p-5">
        <img class="img-fluid w-100 p-3" src="https://pyxis.nymag.com/v1/imgs/a22/179/b205a78510315d932427143ad6b6fb5694-03-homer-simpson-doughnuts.2x.rhorizontal.w700.jpg" alt="Homer eating donut">
      </div>
    </div>
    <div class="rated-donuts-sentence d-flex justify-content-center p-3">
      <p> Check out our top rated donuts:</p>
    </div>
    <div class="justify-content-around d-flex">
          <%  @top_donuts.each do |donut| %>
            <div class="card big-white-container col-3 m-3">
              <div class="card-body">
                <h5><strong><%= donut.name%></strong></h5>
              </div>
              <%= link_to donut_path(donut) do %>
                <%= cl_image_tag(donut.photo.key, width: 600, height: 600, crop: :fill , alt: donut.name, class:"rounded mx-auto d-block img-thumbnail card-img-top" ) %>
              <% end %>
              <div class="card-body">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item"> <%= image_tag "donut-c.png", width: 20, height: 20 %> <%= donut.rating>0 ? "#{donut.rating} (#{donut.number_ratings})" : "N/A" %></li>
                  <% price = donut.price.round(2).to_s.split(".") %>
                  <% if price[1].length == 1 %>
                    <% price[1] = price[1] + "0" %>
                  <%end%>
                  <% price = price.join(".") %>
                  <li class="list-group-item">£ <%= price%></li>
                  <li class="list-group-item"><%= donut.available? ? "Available" : "Not available" %></li>
                  <li class="list-group-item">
                  <% donut.donut_tags.each do |donut_tag| %>
                      <% if donut_tag.tag.name == "vegan"%>
                        <img style="background-color: green;" src="https://res.cloudinary.com/danwlbu2c/image/upload/v1676652300/production/5278701_u0pvgg.png" height="35" width="35">
                      <% end %>
                      <%  if donut_tag.tag.name == "vegetarian"%>
                        <img style="background-color: #64ff33;" src="https://res.cloudinary.com/danwlbu2c/image/upload/v1676652260/production/723734_wtdngc.png" height="35" width="35">
                      <% end %>
                      <%  if donut_tag.tag.name == "gluten free"%>
                        <img style="background-color:#ffd133;" src="https://res.cloudinary.com/danwlbu2c/image/upload/v1676652284/production/4905936_ds74gd.png" height="35" width="35">
                      <% end %>
                      <%  if donut_tag.tag.name == "low fat"%>
                        <img style="background-color: pink;" src="https://res.cloudinary.com/danwlbu2c/image/upload/v1676652316/production/4762115_g99zef.png" height="35" width="35">
                      <% end %>
                  <% end %>
                  </li>
                </ul>
              </div>
            </div>
          <% end %>
      </div>
  </div>
</div>